import { Resend } from 'resend';
import dotenv from 'dotenv';
import databaseService from './database.service.mjs';

dotenv.config();

/**
 * Resolves who a report should go to.
 *
 * Reports used to go to a single EMAIL_RECIPIENT env var, so in a multi-user
 * deployment every user's reports landed in the operator's inbox. The address
 * saved during onboarding (user_preferences.email) is now the source of truth;
 * EMAIL_RECIPIENT remains only as a single-user/dev fallback.
 */
async function resolveRecipient(userId) {
    if (userId) {
        const preferred = await databaseService.getUserEmail(userId);
        if (preferred) return preferred;
    }
    return process.env.EMAIL_RECIPIENT || null;
}

/**
 * Sends a report by email.
 *
 * @param {string} markdown - Report body.
 * @param {string} subject  - Subject context (usually a repository name).
 * @param {string} [userId] - Recipient. Falls back to EMAIL_RECIPIENT when absent.
 */
export async function sendEmail(markdown, subject, userId = null) {
    const recipient = await resolveRecipient(userId);

    if (!recipient) {
        throw new Error(
            userId
                ? 'No email address on file for this user, and EMAIL_RECIPIENT is not set.'
                : 'EMAIL_RECIPIENT is not configured.'
        );
    }

    if (!process.env.RESEND_API_KEY) {
        throw new Error('RESEND_API_KEY is not configured.');
    }

    const resend = new Resend(process.env.RESEND_API_KEY);
    const escapeHtml = (s) => String(s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

    console.log(`✉️ Sending report to ${recipient}...`);

    const { data, error } = await resend.emails.send({
        // Unverified free-tier domains must send from onboarding@resend.dev
        from: process.env.EMAIL_FROM || 'Ulla Britta <onboarding@resend.dev>',
        to: recipient,
        subject: `🤖 Ulla Britta: ${subject}`,
        text: markdown,
        html: `
            <div style="background-color: #f6f8fa; padding: 20px; font-family: sans-serif;">
                <div style="background-color: white; padding: 30px; border-radius: 8px; border: 1px solid #d0d7de;">
                    <pre style="white-space: pre-wrap; font-size: 14px; line-height: 1.5; color: #24292f;">${escapeHtml(markdown)}</pre>
                </div>
                <p style="font-size: 12px; color: #57606a; margin-top: 20px; text-align: center;">
                    Generated by Ulla Britta
                </p>
            </div>
        `,
    });

    if (error) {
        console.error('❌ Resend failed:', error.message);
        throw new Error(error.message);
    }

    console.log(`✅ Email sent (id: ${data?.id})`);
    return { recipient, id: data?.id };
}
