import { Resend } from 'resend';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Sends an autonomous report via Resend.
 * @param {string} markdown - The high-fidelity report in markdown format.
 * @param {string} repository - Repository name for context.
 */
export async function sendEmail(markdown, repository) {
    const resend = new Resend(process.env.RESEND_API_KEY);
    const recipient = process.env.EMAIL_RECIPIENT;

    if (!recipient) {
        throw new Error('EMAIL_RECIPIENT is not configured in Render environment.');
    }

    try {
        console.log(`✉️ Sending Resend report to ${recipient}...`);
        
        const { data, error } = await resend.emails.send({
            // MUST use onboarding@resend.dev for unverified free-tier domains
            from: 'Ulla Britta <onboarding@resend.dev>', 
            to: recipient,
            subject: `🤖 Analysis Report: ${repository}`,
            text: markdown,
            html: `
                <div style="background-color: #f6f8fa; padding: 20px; font-family: sans-serif;">
                    <div style="background-color: white; padding: 30px; border-radius: 8px; border: 1px solid #d0d7de;">
                        <pre style="white-space: pre-wrap; font-size: 14px; line-height: 1.5; color: #24292f;">${markdown}</pre>
                    </div>
                    <p style="font-size: 12px; color: #57606a; margin-top: 20px; text-align: center;">
                        Generated by Ulla Britta v1.0.0 • Autonomous SRE Agent
                    </p>
                </div>
            `,
        });

        if (error) {
            throw new Error(error.message);
        }

        console.log(`✅ Resend Email sent! (ID: ${data.id})`);
    } catch (error) {
        console.error('❌ Resend failed:', error.message);
        throw error; 
    }
}
