const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a PDF report based on AI analysis.
 * @param {Object} analysis - The analysis object from ai.service.js.
 * @returns {Promise<String>} - The path to the generated PDF.
 */
async function generatePDF(analysis) {
  return new Promise((resolve, reject) => {
    try {
      const reportsDir = path.join(process.cwd(), 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir);
      }

      const fileName = `report-${analysis.repoName.replace('/', '-')}-${Date.now()}.pdf`;
      const filePath = path.join(reportsDir, fileName);
      const doc = new PDFDocument({ margin: 50 });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Header
      doc.fontSize(25).text('CodeNarrator Report', { align: 'center' });
      // ... content logic is fine ...
      doc.moveDown();
      doc.fontSize(12).text(`Repository: ${analysis.repoName}`, { align: 'left' });
      doc.text(`Generated: ${new Date(analysis.timestamp).toLocaleString()}`);
      doc.text(`Commits Analyzed: ${analysis.commitCount}`);
      doc.moveDown();
      
      doc.path('M 0 0 L 500 0').stroke();
      doc.moveDown();

      // Content
      doc.fontSize(18).text('Analysis Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).text(analysis.summary, {
        align: 'justify',
        lineGap: 2
      });

      // Footer
      const bottom = doc.page.height - 50;
      doc.fontSize(10).text('Generated by CodeNarrator AI', 50, bottom, { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        console.log(`PDF report generated and saved: ${filePath}`);
        resolve(filePath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (error) {
      console.error('Error generating PDF:', error);
      reject(error);
    }
  });
}

module.exports = { generatePDF };
