/**
 * Ulla Britta Report Generator (Enhanced with Commands)
 */
export class UllaBrittaReportGenerator {
    constructor() {
        this.version = '1.0.1';
        this.baseUrl = process.env.APP_URL || 'https://ulla-britta.onrender.com';
    }

    generate(data) {
        const sections = [];

        sections.push(this.generateHeader(data));
        sections.push(this.generateExecutiveSummary(data));

        // Add the Interactive Command Section if it's a new deployable project
        if (data.deploymentSuggestion) {
            sections.push(this.generateDeploymentCommand(data));
        }

        sections.push(this.generateWhatChanged(data));
        sections.push(this.generateAIAnalysis(data));

        if (data.autoFixApplied) {
            sections.push(this.generateFixDetails(data));
        }

        sections.push(this.generateImpactAssessment(data));
        sections.push(this.generateQualityChecks(data));
        sections.push(this.generateNextSteps(data));
        sections.push(this.generateResources(data));
        sections.push(this.generateFooter(data));

        return sections.join('\n\n---\n\n');
    }

    generateDeploymentCommand(data) {
        const { owner, repo, installationId, provider } = data.deploymentSuggestion;
        const approvalUrl = `${this.baseUrl}/approve-deployment?repo=${repo}&owner=${owner}&installation_id=${installationId}&provider=${provider}`;

        return `## 🚀 Hosting Opportunity Detected!

I've detected that this is a project that can be hosted on **${provider}**, but it doesn't have a live link yet. 

Would you like me to set up the hosting for you automatically?

[**👉 YES, DEPLOY THIS NOW**](${approvalUrl})

*Note: Clicking this will link your GitHub repo to ${provider} and update your repo homepage.*`;
    }

    generateHeader(data) {
        return `# 🤖 Ulla Britta Analysis Report\n\n**Repository:** \`${data.owner}/${data.repo}\`  \n**Commit:** \`${(data.commitSha || '').substring(0, 8)}\`  \n**Branch:** ${data.branch}  \n**Author:** ${data.author}  \n**Analyzed:** ${new Date(data.timestamp).toLocaleString()}`;
    }

    generateExecutiveSummary(data) {
        const confidenceEmoji = this.getConfidenceEmoji(data.confidence);
        const impactEmoji = this.getImpactEmoji(data.impactLevel);
        return `## 📊 Executive Summary\n\n${data.summary}\n\n**Confidence Score:** ${confidenceEmoji} ${data.confidence}%  \n**Impact Level:** ${impactEmoji} ${data.impactLevel}`;
    }

    generateWhatChanged(data) {
        let markdown = `## 🔍 What Changed\n\n### Files Modified (${data.filesChanged?.length || 0})\n\n| File | Changes | Type |\n|------|---------|------|\n`;
        data.filesChanged?.forEach(file => {
            markdown += `| \`${file.path}\` | +${file.additions} -${file.deletions} | ${file.language} |\n`;
        });
        return markdown;
    }

    generateAIAnalysis(data) {
        let markdown = `## 🧠 AI Analysis\n\n### Root Cause\n\n${data.rootCause}\n\n**Error Type:** ${data.errorType}  \n**Location:** \`${data.errorLocation}\`\n`;
        if (data.originalCode && data.fixedCode) {
            const language = this.detectLanguage(data.errorLocation);
            markdown += `\n\`\`\`${language}\n// ❌ Before\n${data.originalCode}\n\n// ✅ After\n${data.fixedCode}\n\`\`\`\n`;
        }
        markdown += `\n### Why This Fix Works\n\n${data.whyItWorks}`;
        return markdown;
    }

    generateFixDetails(data) {
        let markdown = `## ⚡ Fix Details\n\n### Changes Applied\n\n${data.fixDescription || 'Fix was automatically applied.'}\n`;
        if (data.diff) markdown += `\n#### Modified Files\n\n\`\`\`diff\n${data.diff}\n\`\`\`\n`;
        return markdown;
    }

    generateImpactAssessment(data) {
        return `## 🎯 Impact Assessment\n\n### Scope of Changes\n\n- **Lines Changed:** ${data.linesAdded || 0} added, ${data.linesRemoved || 0} removed\n- **Functions Affected:** ${data.functionsAffected || 0}\n\n**Deployment Risk:** ${this.getImpactEmoji(data.deploymentRisk)} ${data.deploymentRisk}`;
    }

    generateQualityChecks(data) {
        return `## ✅ Quality Checks\n\n- **Status:** ${data.buildStatus === 'Success' ? '✅' : '❌'} ${data.buildStatus}`;
    }

    generateNextSteps(data) {
        let markdown = `## 📝 Next Steps\n`;
        data.immediateActions?.forEach(action => { markdown += `- [ ] ${action}\n`; });
        return markdown;
    }

    generateResources(data) {
        return `## 🔗 Resources\n\n- [View Full Diff on GitHub](${data.githubUrl})`;
    }

    generateFooter(data) {
        const statusEmoji = this.getStatusEmoji(data.status);
        return `## 📧 Report Generated By\n\n**Ulla Britta** v${this.version}  \nAutonomous GitHub Healing Agent\n\n**Status:** ${statusEmoji} \`${data.status}\``;
    }

    getConfidenceEmoji(c) { return c >= 90 ? '🟢' : c >= 70 ? '🟡' : '🔴'; }
    getImpactEmoji(l) { return l === 'High' ? '🔴' : l === 'Medium' ? '🟡' : '🟢'; }
    getStatusEmoji(s) { 
        const map = { 'PROCEED': '✅', 'PROCEED WITH CAUTION': '⚠️', 'REQUIRES REVIEW': '🔍', 'DO NOT MERGE': '🛑' };
        return map[s] || '❓';
    }
    detectLanguage(filepath) {
        const ext = filepath?.split('.').pop()?.toLowerCase();
        const map = { 'ts': 'typescript', 'js': 'javascript', 'py': 'python', 'go': 'go' };
        return map[ext] || 'text';
    }
}

const generator = new UllaBrittaReportGenerator();
export function generateReport(data) { return generator.generate(data); }
